1

INSERT INTO AUTOMOVILES(MATRICULA,MARCA,MODELO,COLOR,PRECIO,KILOMETROS,EXTRAS,ALQUILADO)
VALUES("7600CFG","BMW","520TDI","AZUL",95,1200,"AA,EE,DA,CC,CD,ABS",0);


otra formas es sin escribir los valores del automovil:
INSERT INTO AUTOMOVILES
VALUES ('7600CFG','BMW','520TDI',"AZUL",95,1200,"AA,EE,DA,CC,CD,ABS",0);


2

INSERT INTO AUTOMOVILES(MATRICULA,MARCA,MODELO,COLOR,PRECIO,KILOMETROS,EXTRAS,ALQUILADO)
VALUES("2300CFG","CITROEN","C2","GRIS",95,1120,0,85);

3

INSERT INTO AUTOMOVILES(MATRICULA,MARCA,MODELO,COLOR,PRECIO,KILOMETROS,EXTRAS,ALQUILADO)
VALUES("6940BGF","AUDI","A6","NEGRO",120,1000,0,0);

4

INSERT INTO AUTOMOVILES(MATRICULA,MARCA,MODELO,COLOR,PRECIO,KILOMETROS,EXTRAS,ALQUILADO)
VALUES("123BMY","SEAT","TOLEDO","GRIS",95,1000,0,0);

para cambiar datos ... 
UPDATE AUTOMOVILES
SET MATRICULA = '1234BMY'
WHERE MATRICULA = '123BMY';


5
como no existe ese dni, hay que agregarle a clientes, asi que nos lo inventamos

(DNI ESTA EN LAS DOS TABLAS COMO CHAR OSEA QUE TIENE QUE IR ENTRE COMILLAS)

INSERT INTO CONTRATOS (MATRICULA, DNI, FINICIAL, KINICIAL)
VALUES ('4387BDD','02748375', '2007-10-12', 23057);

6


INSERT INTO CONTRATOS (NUMCONTRATO, DNI, MATRICULA, FINICIAL,KINICIAL)
VALUES (50, '00445760', '5678BRZ', CURRENT_DATE(),(SELECT KILOMETROS FROM AUTOMOVILES WHERE MATRICULA = '5678BRZ'));


7

INSERT INTO CONTRATOS (DNI, MATRICULA, FINICIAL)
VALUES ('11223344', '3765BSD', CURRENT_DATE());

8

INSERT INTO CLIENTES(DNI,APELLIDOS,NOMBRE,DIRECCION,LOCALIDAD,CARNET,FECHAEXP)
VALUES('98765432',"motos garcia","Pablo","C/hormigas 3","Madrid","B", '1989-05-12');


INSERT INTO CONTRATOS (DNI, MATRICULA, FINICIAL)
VALUES ('98765432', '3765BSD', CURRENT_DATE());

9.
UPDATE CONTRATOS
SET NUMCONTRATO=7
WHERE NUMCONTRATO=9;
UPDATE CONTRATOS
SET NUMCONTRATO=8
WHERE NUMCONTRATO=50;
UPDATE CONTRATOS
SET NUMCONTRATO=17
WHERE NUMCONTRATO=16;




INSERT INTO CONTRATOS(NUMCONTRATO,MATRICULA,DNI,FINICIAL)
VALUES (16,"1732CBS","00371569", CURRENT_DATE());


10


DELETE FROM CONTRATOS2 WHERE NUMCONTRATO =4;  //PARA BORRAR DATOS

Este comando actualiza los valores de la columna "NUMCONTRATO" 
de la tabla "CONTRATOS2" sumándoles 30.
 Esto significa que cada fila tendrá 30 añadidos a su valor original
 en la columna "NUMCONTRATO". Por ejemplo, si la fila actualmente tiene el valor "5" en "NUMCONTRATO", 
después de ejecutar este comando, el valor será "35".
UPDATE CONTRATOS2 SET NUMCONTRATO=NUMCONTRATO+30;

INSERT INTO CONTRATOS(MATRICULA,DNI,FINICIAL,FFINAL,KINICIAL,KFINAL)
SELECT MATRICULA,DNI,FINICIAL,FFINAL,KINICIAL,KFINAL FROM CONTRATOS2;

11

PARA CAMBIAR EL DNI POR OTRO

UPDATE CLIENTES SET DNI= " " WHERE DNI= " ";

INSERT INTO CLIENTES(DNI,APELLIDOS,NOMBRE,DIRECCION,LOCALIDAD,CARNET,FECHAEXP)
VALUES('12348630',"Garcia Ostos","Macarena","C/bases de datos","Pamplona","B", '2002-05-12');

 
 INSERT INTO CONTRATOS(MATRICULA, DNI,FINICIAL,KINICIAL)
 VALUES((SELECT MATRICULA FROM AUTOMOVILES WHERE MODELO='500 E'),'12348630',NOW(),(SELECT KILOMETROS FROM AUTOMOVILES WHERE MODELO='500 E'));
 



12


INSERT INTO CONTRATOS(MATRICULA,DNI,FINICIAL,KINICIAL)
VALUES('4387BDD',(SELECT DNI FROM CLIENTES 
WHERE NOMBRE ='Natalia' AND APELLIDOS='Montoya'),NOW(),(SELECT KILOMETROS FROM AUTOMOVILES WHERE MATRICULA ='4387BDD'));


13




INSERT INTO CONTRATOS (MATRICULA, DNI, FINICIAL, KINICIAL)
SELECT AUTOMOVILES.MATRICULA, CLIENTES.DNI, CURDATE(), 0
FROM AUTOMOVILES, CLIENTES
WHERE (AUTOMOVILES.COLOR = 'AZUL' OR AUTOMOVILES.COLOR = 'ROJO')
AND CLIENTES.NOMBRE = 'NATALIA' AND CLIENTES.APELLIDOS = 'MONTOYA';




14

DELETE FROM CONTRATOS
WHERE NUMCONTRATO
BETWEEN 22 AND 27;

DELETE FROM CONTRATOS
WHERE NUMCONTRATO>=57;


15(ni idea)

SELECT * FROM 'CLIENTES' INTO OUTFILE "C:\BD\Ejercicio15";


16(ni idea)

SELECT NOMBRE,APELLIDOS,PRECIO*DATEDIFF(FFINAL,FINICIAL) AS IMPORTE
INTO OUTFILE "EJERCICIO.16TXT"
FROM CLIENTES NATURAL JOIN CONTRATOS NATURAL JOIN AUTOMOVILES
WHERE FFINAL IS NOT NULL;

17


UPDATE CONTRATOS
SET FFINAL="2022/04/19",KFINAL=24756
WHERE NUMCONTRATO=16;

18
UPDATE CONTRATOS
SET KFINAL=12267
WHERE NUMCONTRATO=17;

19

UPDATE AUTOMOVILES
SET COLOR='ROJO'
WHERE MARCA='FORD' AND MODELO='FOCUS';

20

UPDATE CONTRATOS
SET FFINAL= ADDDATE(FFINAL,7),
KFINAL =KINICIAL+2200
WHERE NUMCONTRATO=18  OR NUMCONTRATO =19;

21

UPDATE AUTOMOVILES
SET ALQUILADO=FALSE;

22

UPDATE AUTOMOVILES NATURAL JOIN CONTRATOS
SET ALQUILADO=TRUE
WHERE FFINAL IS NULL;

23

INSERT INTO CONTRATOS(MATRICULA,DNI,FINICIAL,KINICIAL)
VALUES('4738CBJ','09856064',CURDATE(),
(SELECT KILOMETROS FROM AUTOMOVILES WHERE MATRICULA='4738CBJ'));


24

UPDATE CONTRATOS
SET NUMCONTRATO=NUMCONTRATO+20
WHERE NUMCONTRATO BETWEEN 20 AND 23;

25
(NO SE PUEDE HACER)

UPDATE CONTRATOS
SET NUMCONTRATO=6
WHERE NUMCONTRATO=16; 

26
(NO SE PUEDE HACER)

UPDATE CONTRATOS
SET MATRICULA='5071BLH'
WHERE NUMCONTRATO=15;

27

(NOSEPUEDE PORQUE HAY QUE CAMBIAR LA RELACION O BORRAR EL COTRATO)

UPDATE AUTOMOVILES
SET MATRICULA='4783CBJ'
WHERE MARCA='AUDI' AND MODELO='A3';


----------------------------------------

PARA CAMBIAR UNA RELACION (PRIMERO BORRAR)

ALTER TABLE CONTRATOS
DROP FOREIGN KEY contratos_ibfk_2;

PARA CREAR UNA CLAVE AJENA

ALTER TABLE CONTRATOS
ADD FOREIGN KEY (MATRICULA) REFERENCES
AUTOMOVILES(MATRICULA)ON UPDATE CASCADE ON
DELETE CASCADE;


---------------------------------------------

SHOW CREATE TABLE CONTRATOS; (PARA BUSCAR  LA CLAVE FORANEA)


28

UPDATE AUTOMOVILES NATURAL JOIN CONTRATOS
SET KILOMETROS=KFINAL
WHERE NUMCONTRATO=15; 

29

UPDATE AUTOMOVILES
SET PRECIO=PRECIO*1.02;

30

UPDATE AUTOMOVILES NATURAL JOIN CONTRATOS
SET KILOMETROS = KFINAL
WHERE FFINAL BETWEEN '2017-03-04' AND '2017-04-15';