

USE DATABASE TEST;


1

CREATE TABLE MASCOTAS(
ID INT(5) AUTO_INCREMENT,
NOMBRE VARCHAR(15)NOT NULL,
RAZA VARCHAR(15) DEFAULT 'PERRO',
FNACIMIENTO DATE NOT NULL,
PRIMARY KEY(ID));


2

//INTRODUCE 5 REGISTROS 


INSERT INTO MASCOTAS(NOMBRE,RAZA,FNACIMIENTO)
VALUES('BOBY','GATO','2022-01-12');

INSERT INTO MASCOTAS(NOMBRE,RAZA,FNACIMIENTO)
VALUES('REX','PERRO','2022-05-12');
INSERT INTO MASCOTAS(NOMBRE,RAZA,FNACIMIENTO)
VALUES('PICACHU','GATO','2020-04-20');

INSERT INTO MASCOTAS(NOMBRE,RAZA,FNACIMIENTO)
VALUES('CHARMANDER','PERIQUITO','2020-11-12');

INSERT INTO MASCOTAS(NOMBRE,RAZA,FNACIMIENTO)
VALUES('SQUIRTLE','GATO','2019-12-12');


3


Alter table mascotas
add column Raza varchar(10);

truncate mascotas;


4 HACER UNA COPIA

5
START TRANSACTION;

TRUNCATE MASCOTAS;

12

VALOR DE AUTOCOMIT

select @@autocommit;

13

SET AUTOCOMMIT=0;


14 

DELETE FROM MASCOTAS;

15

PARA DESHACER LA INFORMACION DAR A 

ROLLBACK

16

//BORRA LAS 3 PRIMERAS MASCOTAS


DELETE FROM MASCOTAS
WHERE ID <=3;


ROLLBACK;

20



DELETE FROM MASCOTAS
WHERE ID=1;


23

//lista los automoviles sobre los 
que no se han efectuado ningun contrato


//CORRECTA

SELECT AUTOMOVILES.* 
FROM AUTOMOVILES LEFT JOIN CONTRATOS
ON AUTOMOVILES.MATRICULA=CONTRATOS.MATRICULA         
WHERE NUMCONTRATO IS NULL;

1235BMK

UPDATE AUTOMOVILES SET MATRICULA="1235BMK" 
WHERE MARCA="AUDI" AND MODELO="A6";




24
//lista el numero de cohes contratados de cada marca


SELECT COUNT(*),MARCA
FROM CONTRATOS;

SELECT COUNT(AUTOMOVILES.MARCA) AS "CANTIDAD DE COCHES",MARCA
FROM AUTOMOVILES JOIN CONTRATOS ON AUTOMOVILES.MATRICULA=CONTRATOS.MATRICULA
GROUP BY MARCA
HAVING COUNT(AUTOMOVILES.MATRICULA)>3;

-------MARCAS CONTRATADAS NO ESTEN CONTRATASDAS!!!!

SELECT COUNT(AUTOMOVILES.MATRICULA) AS "CANT CONTRATADAS",MODELO
FROM AUTOMOVILES NATURAL JOIN CONTRATOS
GROUP BY MODELO
HAVING COUNT(AUTOMOVILES.MATRICULA)<3;




26

-poner alquilado a cero poner alquilado ;
PONER ALQUILADO A 1 SI ESTAN CONTRATADOS SIN FECHA INICIAL -


UPDATE  AUTOMOVILES SET ALQUILADO=0;
UPDATE AUTOMOVILES AS ALJOIN CONTRATOS AS C1
ON A1.MATRICULA=C1.MATRICULA SET ALQUILADO=1
WHERE FFINAL IS NULL ;


SET ALQUILADO=1

27

//FOREIG UN CAMPO DE UNA TABLA QUE VAYA CON LA PRIMARY KEY DE LA OTRA



-CREAR LA TABLA CLIENTES CON EL ID,NOMBRE,FECHAINSCRIPCION
-AÑADIR EL CAMPO AMO
-PONER QE EL CAMPO AMO SEA CLAVE AJENA



CREATE TABLE CLIENTES(
ID SMALLINT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(25),
FINSCRIP DATE);


ALTER TABLE MASCOTAS
ADD AMO VARCHAR(20);

ALTER TABLE MASCOTAS
MODIFY AMO SMALLINT;


(CAMBIAR ESTO)
ALTER TABLE MASCOTAS
ADD FOREIGN KEY(AMO)REFERENCES TABLE CLIENTES(ID)
ON DELETE CASCADE ON UPDATE CASCADE;






25

lista los numeros de los 5 ultimos contratos y la fecha inicial en que se hicieron
con el formato dd/mm//aaaa




//PARA CAMBIAR LA ESTRUCTURA

ALTER TABLE MASCOTAS
ADD ESPECIE VARCHAR (20)DEFAULT "CAIMAN";


UPDATE MASCOTAS SET  ESPACIE="PERRO" WHERE ID IN(1,2);



//PARA CAMBIAR EL NOMBRE 


UPDATE MASCOTAS SET NOMBRE='Casio' WHERE ID=3;



---------------------------


//PARA CAMBIAR EL ID


UPDATE CLIENTES SET SET ID=3 WHERE ID=1;



INSERT INTO CLIENTES(NOMBRE,FINSCRIP)
VALUES('JUAN','2018-01-12');
INSERT INTO CLIENTES(NOMBRE,FINSCRIP)
VALUES('EVA','2020-09-21');
INSERT INTO CLIENTES(NOMBRE,FINSCRIP)
VALUES('PEDRO','2023-01-03');
INSERT INTO CLIENTES(NOMBRE,FINSCRIP)
VALUES('LUIS','2018-01-12');

SELECT C.NOMBRE,COUNT(C.ID)AS NUMERO
FROM CLIENTES C LEFT JOIN MASCOTAS ON C.ID=AMO GROUP BY C.ID;




//MASCOTA MAS VIEJA DE CADA ESPECIE



(ESTA ESTA BIEN)
SELECT NOMBRE,YEAR(CURDATE())-YEAR(FNACIMIENTO)ANTIGUEDAD
FROM MASCOTAS ORDER BY FNACIMIENTO ASC; 

(ESTE DE ABAJO ES EL CORRECTO DE ALBERTO)            

SELECT RAZA, MAX(EDAD)AS MAYOR FROM MASCOTAS GROUP BY RAZA;


//MEDIA DE EDAD DE LAS MASCOTAS DE CADA ESPECIE


SELECT C.NOMBRE,AVG(EDAD)AS EDAD_MEDIA 
FROM CLIENTES AS C JOIN MASCOTAS ON AMO=C.ID GROUP BY C.ID;




//SUMA DE LAS EDADES DE LAS MASCOTAS DE CADA ESPECIE MENOS LAS DEL CLIENTES3 , QUE PASEN DE 10 AÑOS

(SALE ALGO RARO)

SELECT RAZA,SUM(EDAD)AS TOTAL FROM CLIENTES JOIN MASCOTAS ON AMO=CLIENTES.ID
WHERE CLIENTES.ID<>3 GROUP BY RAZA HAVING SUM(EDAD)>10;



//AÑADIR  LA TABLA

ALTER TABLE MASCOTAS 
ADD EDAD INT DEFAULT 2;

UPDATE MASCOTAS
SET EDAD=5
WHERE ID<4;


(tengo que insertar los AMO a las MASCOTAS)

UPDATE MASCOTAS
SET AMO = (SELECT ID FROM CLIENTES WHERE NOMBRE = 'JUAN')
WHERE NOMBRE = 'BOBY';

UPDATE MASCOTAS
SET AMO = (SELECT ID FROM CLIENTES WHERE NOMBRE = 'EVA')
WHERE NOMBRE = 'SQUIRTLE';

UPDATE MASCOTAS
SET AMO = (SELECT ID FROM CLIENTES WHERE NOMBRE = 'PEDRO')
WHERE NOMBRE = 'REX';
UPDATE MASCOTAS
SET AMO = (SELECT ID FROM CLIENTES WHERE NOMBRE = 'LUIS')
WHERE NOMBRE = 'PICACHU';

UPDATE MASCOTAS
SET AMO = (SELECT ID FROM CLIENTES WHERE NOMBRE = 'LUIS')
WHERE NOMBRE = 'CHARMANDER';









