//LA MECANICA DE ROLLBACK

START TRANSACTION;

SELECT * FROM CONTRATOS;

DELETE FROM CONTRATOS
WHERE NUMCONTRATOS=2;

SELECT * FROM CONTRATOS;

ROLLBACK;

START TRANSACTION;



-------------------------

START TRANSACTION;

SELECT * FROM CONTRATOS;

DELETE FROM CONTRATOS
WHERE NUMCONTRATOS=2;

SELECT * FROM CONTRATOS;

EXIT;


----------------------------------------------------------------------

PRACTICA 9

1

START TRANSACTION;

2

USE ALQUILERES;



DELETE FROM CONTRATOS
WHERE NUMCONTRATO=50;

3

DELETE FROM CONTRATOS
WHERE NUMCONTRATO>24;

4

Eliminar en la tabla CONTRATOS los contratos realizados sobre algún BMW

DELETE FROM contratos
WHERE matricula IN (SELECT matricula FROM automoviles WHERE marca = 'BMW');

--------------

DELETE contratos
FROM contratos
JOIN automoviles
ON contratos.matricula = automoviles.matricula
WHERE automoviles.marca = 'BMW';


5
Para eliminar los contratos realizados por los clientes con apellido "Tirador Gutiérrez" utilizando un JOIN, 
primero debes unir las tablas "contratos" y "clientes" a través de un campo común, como por ejemplo el DNI del cliente.
Entonces en la cláusula WHERE especificas que quieres eliminar los contratos que tengan el mismo DNI que los clientes con apellido "Tirador Gutiérrez".

DELETE FROM CONTRATOS WHERE DNI IN (SELECT DNI FROM CLIENTES WHERE APELLIDOS= 'FUENTES ROJAS');



DELETE CONTRATOS FROM CONTRATOS 
JOIN clientes ON contratos.DNI = clientes.DNI
WHERE clientes.APELLIDOS ='TIRADOR GUTIERREZ';

Ten en cuenta que es importante que el campo "DNI" exista en ambas tablas y que estén relacionadas entre sí.

6
Eliminar en la tabla CLIENTES los clientes de apellidos Fuentes Rojas.
SELECT * FROM clientes WHERE apellidos = 'Fuentes Rojas';


DELETE FROM clientes WHERE apellidos = 'Fuentes Rojas';
DELETE FROM clientes WHERE apellidos LIKE'Fuentes%';    //PARA BORRAR TODOS LOS FUENTES
                                
7

Eliminar de la tabla CONTRATOS los contratos realizados por Ismael Poza
Rincón sobre el automóvil Audi A4. (Si el apellido del cliente no es correcto
corrígelo)

UPDATE CLIENTES SET APELLIDOS = 'POZA RINCON'
WHERE NOMBRE ='ISMAEL';


DELETE FROM CONTRATOS
WHERE DNI =(SELECT DNI FROM CLIENTES WHERE APELLIDOS='POZA RINCON')
AND MATRICULA IN (SELECT MATRICULA FROM AUTOMOVILES WHERE MARCA='AUDI' AND MODELO='A4');


7B

//MEJOR USAR EL INNER JOIN ()


DELETE CONTRATOS
CONTRATOS NATURAL JOIN CLIENTES NATURAL JOIN AUTOMOVILES
WHERE APELLIDOS='POZA RAMON' AND MODELO='A4' AND MARCA='AUDI';

--------------------------------------------------------------------

DELETE CONTRATOS 
FROM CLIENTES INNER JOIN CONTRATOS ON CLIENTES.DNI=CONTRATOS.DNI
INNER JOIN AUTOMOVILES ON CONTRATOS.MATRICULA=AUTOMOVILES.MATRICULA;


8

SELECT * //PARA VER ANTES DE BORRAR

DELETE A1
FROM AUTOMOVILES A1,AUTOMOVILES A2
WHERE A1.PRECIO>A2.PRECIO AND A2.MARCA='MERCEDES' AND A2.MODELO='500 E';


9

DELETE FROM CONTRATOS2;


10


START TRANSACTION;

DELETE FROM CONTRATOS2
WHERE DNI= '09856064';
DELETE FROM CLIENTES
WHERE DNI='09856064';


ALTER TABLE CONTRATOS
DROP FOREIGN KEY CONTRATOS_IBFK_1;
ALTER TABLE CONTRATOS
ADD FOREIGN KEY (DNI)
REFERENCES CLIENTES(DNI)ON
DELETE CASCADE ON UPDATE
CASCADE;


11 

//primero saber en que tabla esta




DELETE FROM CLIENTES 
WHERE APELLIDO LIKE 'DORADO%' AND NOMBRE='MARIANO';


12


DELETE FROM CONTRATOS WHERE
FFINAL IS NOT NULL AND MATRICULA IN
(SELECT MATRICULA FROM AUTOMOVILES WHERE MARCA='SEAT');


---------
//SE PUEDE HACER TAMBINE CON EL NATURAL JOIN

DELETE CONTRATOS FROM CONTRATOS NATURAL JOIN AUTOMOVILES
WHERE FFINAL IS NOT NULL AND MARCA='SEAT';



//CON INNNER JOIN


DELETE CONTRATOS 
FROM CONTRATOS C INNER JOIN AUTOMOVILES A
ON C.MATRICULA=A.MATRICULA;



13


DELETE CONTRATOS
FROM CONTRATOS NATURAL JOIN AUTOMOVILES
WHERE FFINAL IS NULL AND MARCA='SEAT';

DELETE C
FROM CONTRATOS C INNER JOIN AUTOMOVILES A ON 
C.MATRICULA=A.MATRICULA;


14

DELETE FROM AUTOMOVILES
WHERE MARCA='SEAT';
SELECT * FROM AUTOMOVILES
WHERE MARCA='SEAT';

15

DELETE FROM CLIENTES
WHERE LOCALIDAD <>'CUENCA' AND 
LOCALIDAD<>'TOLEDO'


DELETE CONTRATOS
FROM CONTRATOS NATURAL JOIN CLIENTES
WHERE LOCALIDAD NOT IN ('CUENCA','TOLEDO');

16

DELETE FROM CONTRATOS;

17

DELETE FROM CLIENTES;


18

ROLLBACK;


19


SET AUTOCOMMIT=0;

20

INSERT INTO AUTOMOVILES
VALUES('4578ZXB','FORD','MONDEO','GRIS',50,1000,'AA,ABS',FALSE);

INSERT INTO CONTRATOS(MATRICULA,DNI,FINICIAL,KINICIAL)
VALUES('4578ZXB','09856064',CURDATE(),1000);


21

ROLLBACK;


22



23



24

set autocommit=1;
star transaction;







select @@autocommit;

















25  
    lISTADO DE AUTOMOVILES CON UN PRECIO SUPERIOR A LA MEDIA DE SU MARCA
	
	SELECT * FROM AUTOMOVILES A1
	WHERE A1.PRECIO >
	(SELECT AVG(PRECIO)FROM AUTOMOVILES A2
	WHERE A1.MARCA=A2.MARCA );
	
	SELECT A1.MARCA,A1.PRECIO,
	
	
	
	
	
	
	
	-------------------------------------
	
	
	Ejercicio de repaso.
	
	¿que automoviles no han sido nunca contratados?
	
	LEFT JOIN
	
	SELECT * FROM AUTOMOVILES
	WHERE ALQUILADO=FALSE;