CREATE DATABASE ALQUILERES;
USE ALQUILERES;
SHOW TABLES;
CREATE TABLE MARCAS (
MARCA VARCHAR(15),
NUMERO TINYINT(2),
PRIMARY KEY (NUMERO),
UNIQUE(MARCA));

CREATE TABLE AUTOMOVILES (
MATRICULA CHAR(7),
MARCA VARCHAR(15) NOT NULL,
MODELO VARCHAR(20) NOT NULL,
COLOR VARCHAR(15),
PRECIO DECIMAL(5,2) NOT NULL,
KILOMETROS INT(6),
EXTRAS VARCHAR(20),
ALQUILADO BOOLEAN DEFAULT False,
PRIMARY KEY (MATRICULA),
FOREIGN KEY (MARCA) REFERENCES MARCAS (MARCA));


CREATE TABLE CLIENTES (
DNI CHAR(9),
APELLIDOS VARCHAR(25) NOT NULL,
NOMBRE VARCHAR(15) NOT NULL,
DIRECCION VARCHAR(40),
LOCALIDAD VARCHAR(15),
CARNET CHAR(2) NOT NULL,
FECHAEXP DATE NOT NULL,
PRIMARY KEY (DNI));

CREATE TABLE CONTRATOS (
NUMCONTRATO INT(5) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
MATRICULA CHAR(7) NOT NULL,
DNI CHAR(9) NOT NULL,
FINICIAL DATE NOT NULL,
FFINAL DATE,
KINICIAL INT(6) NOT NULL,
KFINAL INT(6),
FOREIGN KEY (DNI) REFERENCES CLIENTES(DNI),
FOREIGN KEY(MATRICULA) REFERENCES
AUTOMOVILES(MATRICULA)ON DELETE CASCADE ON UPDATE RESTRICT

);

CREATE TABLE CONTRATOS2 LIKE CONTRATOS;
CREATE TABLE CONTRATOS3 LIKE CONTRATOS;
CREATE TABLE CONTRATOS4 LIKE CONTRATOS;




LOAD DATA LOCAL INFILE "C:/BD/ALQUILERES/Clientes.txt"
INTO TABLE Clientes
LINES TERMINATED BY "\r\n"
IGNORE 1 LINES;


LOAD DATA LOCAL INFILE "C:/BD/ALQUILERES/AUTOMOVILES.txt"
INTO TABLE AUTOMOVILES
LINES TERMINATED BY "\r\n"
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE "C:/BD/ALQUILERES/Marcas.txt"
INTO TABLE Marcas
LINES TERMINATED BY "\r\n"
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE "C:/BD/ALQUILERES/contratos.txt"
INTO TABLE contratos
LINES TERMINATED BY "\r\n"
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE "C:/BD/ALQUILERES/contratos2.txt"
INTO TABLE contratos2
LINES TERMINATED BY "\r\n"
IGNORE 1 LINES;

CREATE TABLE CONTRATOS3 LIKE CONTRATOS;

LOAD DATA LOCAL INFILE "C:/BD/ALQUILERES/contratos3.txt"
INTO TABLE contratos3
LINES TERMINATED BY "\r\n"
IGNORE 1 LINES;


INSERT INTO CONTRATOS(MATRICULA,DNI,FINICIAL,KINICIAL)
VALUES ("1234BMY", "37409800","2009-07-10", 22561),
("2058CGF", "00371569","2009-07-11",9736),
("3273BGH", "24589635","2009-08-11",17368),
("5573BFS","00445760","2009-08-15",28500),
("7839CDR","28759595","2009-10-15",15873),
("8795BTK","12348630","2009-11-16",46980),
("2123BTB","43809540","2009-11-16",34323);


mysqldump -u root -p ALQUILERES>copiaAlq.sql


mysql>source 'c:/BD/COPIA.SQL'


mysqldump -u root -p TEST>copiaSeg.sql