

1
CREATE DATABASE PRUEBAS1;
USE PRUEBAS1;

2

CREATE TABLE ALUMNOS_FRANCES(
NUMAL INT (6)DEFAULT 0,
NOMAL VARCHAR(20),
LOCALIDAD VARCHAR(20),
PRIMARY KEY(NUMAL));

3

CREATE TABLE ALUMNOS_INGLES(
NUMAL INT(6)DEFAULT 0,
NOMBREREAL VARCHAR(20),
CIUDAD VARCHAR(20),
PRIMARY KEY(NUMAL));


4

CREATE TABLE EMPLEADOS(
NUMEMP INT(6)DEFAULT 0,
NOMBREEMP VARCHAR(20),
CATEGORIA VARCHAR(15),
PRIMARY KEY(NUMEMP));

5

CREATE TABLE NOTAS(
NUMERO INT DEFAULT 0 PRIMARY KEY,
NOTA1 INT,
NOTA2 INT);

6

LOAD DATA LOCAL INFILE 'C:/BD/PRUEBAS1/NOTAS.TXT'
INTO TABLE NOTAS 
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'C:/BD/PRUEBAS1/ALUMNOS_FRANCES.TXT'
INTO TABLE ALUMNOS_FRANCES
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'C:/BD/PRUEBAS1/ALUMNOS_INGLES.TXT'
INTO TABLE ALUMNOS_INGLES 
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'C:/BD/PRUEBAS1/EMPLEADOS.TXT'
INTO TABLE EMPLEADOS
IGNORE 1 LINES;


9
// APARECEN LAS DOS TABLAS SIN REPETICIONES

SELECT * FROM ALUMNOS_INGLES
UNION 
SELECT * FROM ALUMNOS_FRANCES;

10


//PARA QUE SE REPITAN TODAS. 

SELECT * FROM ALUMNOS_INGLES
UNION ALL
SELECT * FROM ALUMNOS_FRANCES;


11

//

SELECT NUMAL,NOMBREREAL FROM ALUMNOS_INGLES
UNION
SELECT NUMAL,NOMAL FROM ALUMNOS_FRANCES;

12
SELECT NUMAL, NOMBREREAL,CIUDAD FROM ALUMNOS_INGLES
WHERE CIUDAD='SANTANDER'
UNION
SELECT NUMAL,NOMAL,LOCALIDAD FROM ALUMNOS_FRANCES
WHERE LOCALIDAD='SANTANDER';

----------
(SELECT NUMAL,NOMBREREAL,CIUDAD FROM ALUMNOS_INGLES
WHERE CIUDAD='SANTANDER')
UNION
(SELECT NUMAL,NOMAL,LOCALIDAD FROM ALUMNOS_FRANCES
WHERE LOCALIDAD='SANTANDER');


13

SELECT * FROM ALUMNOS_INGLES,NOTAS;

14

SELECT NUMAL,NOTA1,NOTA2 FROM ALUMNOS_INGLES CROSS JOIN NOTAS;

15

SELECT NUMAL,NOTA1,NOTA2 FROM ALUMNOS_INGLES CROSS JOIN NOTAS
WHERE NUMAL=NUMERO;


16

SELECT NUMAL,NOTA1,NOTA2 FROM ALUMNOS_INGLES CROSS JOIN 
NOTAS WHERE NUMAL=NUMERO;

17

SELECT NUMAL,NOTA1,NOTA2 FROM ALUMNOS_INGLES CROSS JOIN 
NOTAS WHERE NUMAL=NUMERO AND CIUDAD='TORRELAVEGA';

18

SELECT NUMAL,NOTA1,NOTA2 FROM ALUMNOS_INGLES CROSS JOIN 
NOTAS WHERE NUMAL=3 && NUMERO=3;


SELECT FLOOR(RAND()*6)+1;