1
SELECT COUNT(*) FROM CONTRATOS;

SELECT COUNT(FFINAL) FROM CONTRATOS;

2

SELECT COUNT(*) AS TOTAL, LOCALIDAD FROM CLIENTES
GROUP BY LOCALIDAD;

Si no te cuerdas de los campos

DESC CLIENTES;

3

SELECT COUNT(*) NUMCLIENTES, LOCALIDAD FROM CLIENTES
WHERE CARNET = "B"
GROUP BY LOCALIDAD;

4

(EXCEPTO MADRID)    ---->   <>

SELECT COUNT(*)TOTAL, LOCALIDAD FROM CLIENTES
WHERE LOCALIDAD <> 'MADRID'
GROUP BY LOCALIDAD;

-------------------------

SELECT COUNT(*) TOTAL, LOCALIDAD
FROM CLIENTES
GROUP BY LOCALIDAD
HAVING LOCALIDAD <> 'MADRID';

5

SELECT * FROM AUTOMOVILES
WHERE PRECIO > (SELECT PRECIO FROM AUTOMOVILES
WHERE MATRICULA = '3765BSD');

6

SELECT COUNT(*)TOTAL, LOCALIDAD FROM CLIENTES
WHERE CARNET = 'B'
GROUP BY LOCALIDAD
HAVING COUNT(*)>=1;

7

SELECT MATRICULA,FINICIAL FROM CONTRATOS
ORDER BY FINICIAL DESC LIMIT 3;

8

SELECT MARCA, MAX(PRECIO) FROM AUTOMOVILES
GROUP BY MARCA;

9

//LA DE VICTOR
SELECT MARCA, MAX(PRECIO),AVG(PRECIO) FROM AUTOMOVILES
GROUP BY MARCA
HAVING AVG(PRECIO)<=100;

10(NO SE)

SELECT LOCALIDAD, CARNET, COUNT(*)TOTAL
FROM CLIENTES
GROUP BY LOCALIDAD, CARNET;


11
SELECT DNI, COUNT(*) FROM CONTRATOS
GROUP BY DNI
HAVING COUNT(*)=                      );


(SELECT COUNT(*) TOTAL FROM CONTRATOS
GROUP BY DNI ORDER BY TOTAL  DESC LIMIT 1);


 (SELECT COUNT(*)GROUP BY DNI FROM CONTRATOS
ORDER BY COUNT(*) DESC LIMIT 1);                         //NO FUNCIONA


12


SELECT YEAR(MIN(FECHAEXP)),LOCALIDAD
FROM CLIENTES
GROUP BY LOCALIDAD;

13
PARA VER CUANTS VEHICULOS HAY DE CADA MARCA EN LA TABLA

SELECT MARCA,COUNT(*)
FROM AUTOMOVILES
GROUP BY MARCA;


14

SELECT YEAR (MIN(FECHAEXP)),LOCALIDAD,CARNET
FROM CLIENTES
GROUP BY LOCALIDAD, CARNET;

15

SELECT AVG(PRECIO)'PRECIO MEDIO' 
FROM AUTOMOVILES;

16


SELECT AVG(PRECIO),MARCA FROM AUTOMOVILES
GROUP BY MARCA;

17


------

SELECT FINICIAL,SUM(PRECIO*DATEDIFF(FFINAL,FINICIAL))
FROM CONTRATOS C INNER JOIN AUTOMOVILES A ON C.MATRICULA=A.MATRICULA
GROUP BY FINICIAL;

----

TODO EL DINERO QUE HAS HECHO EN AÑOS

SELECT YEAR(FINICIAL),SUM(PRECIO*DATEDIFF(FFINAL,FINICIAL)) TOTAL
FROM CONTRATOS C INNER JOIN AUTOMOVILES A ON C.MATRICULA=A.MATRICULA
GROUP BY YEAR (FINICIAL);


18

SELECT MATRICULA, DATEDIFF(FFINAL,FINICIAL) AS DIAS
FROM CONTRATOS
WHERE DATEDIFF(FFINAL,FINICIAL)>5;


19

SELECT NOMBRE, APELLIDOS,YEAR(CURDATE())-YEAR(FECHAEXP)ANTIGUEDAD
FROM CLIENTES;


----

DATEDIFF (CURDATE(),FECHAEXP)
YEAR(CURDATE())-YEAR(FECHAEXP);


20

SELECT YEAR (CURDATE())-YEAR(FECHAEXP)
FROM CLIENTES;

21
SELECT CONCAT(NOMBRE," ",APELLIDOS)AS NOMBRE
FROM CLIENTES
WHERE FECHAEXP = (SELECT MIN(FECHAEXP) 
FROM CLIENTES);

--------

SELECT NOMBRE, APELLIDOS FROM CLIENTES
ORDER BY FECHAEXP LIMIT 1;

22


SELECT NUMCONTRATO, DATEDIFF(FFINAL,FINICIAL)*PRECIO
AS IMPORTE
FROM CONTRATOS NATURAL JOIN AUTOMOVILES
ORDER BY IMPORTE DESC LIMIT 1;

22B

SELECT NUMCONTRATO FROM CONTRATOS
NATURAL JOIN AUTOMOVILES WHERE 
DATEDIFF(FFINAL,FINICIAL)*PRECIO=(SELECT MAX(DATEDIFF(FFINAL,FINICIAL)*PRECIO) FROM CONTRATOS NATURAL JOIN AUTOMOVILES);

23
(ESTA MAL)

SELECT NUMCONTRATO,NOMBRE, APELLIDOS,DATEDIFF(FFINAL,FINICIAL)*PRECIO-IMPORTE
FROM CONTRATOS NATURAL JOIN CLIENTES NATURAL JOIN AUTOMOVILES
ORDER BY IMPORTE DESC LIMIT 1;


24 

SELECT SUM(KILOMETROS)AS TOTAL_KMS
FROM AUTOMOVILES  WHERE ALQUILADO = FALSE;



25
SELECT SUM(KILOMETROS) TOTAL_KMS,MARCA FROM AUTOMOVILES
GROUP BY MARCA;

